app:
  default-language: english

security:
  jwt:
    expiration-time: 3600000
    secret-key: fddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddsdfssssssssss


spring:
  profiles.active: dev
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    driverClassName: org.postgresql.Driver
    password: to_be_set
    url: jdbc:postgresql://<to-be-set>/plate_drop
    username: to_be_set
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        generate-statistics: true
        format_sql: true
        default_schema: public
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 10
    hibernate:
      ddl-auto: update

  security:
    user:
      name: admin
      password: admin